In [11]:
import numpy as np
import math

In [30]:
class nQubit:
  """The simplest abstraction for the Quantum Equivalent of a bit"""
  def __init__(self, qubitmap, system):
    self.qubit = 

In [31]:
a = 1./math.sqrt(2)
b = 1.j/math.sqrt(2)
q1 = Qubit(a, b)

0.9999999999999998 0.7071067811865475 0.7071067811865475 0.7071067811865475 0.7071067811865475j


In [32]:
q1.display()

0.7071067811865475|0> + 0.7071067811865475j|1>


In [160]:
class d2Unitary:
  """The simplest abstraction for the Quantum Equivalent of a bit"""
  def i(self):
    return np.eye(2)

  def x(self):
    pauli_x = np.array([[0, 1],
                        [1, 0]])
    return pauli_x
  
  def y(self):
    pauli_y = np.array([[0, -1j],
                        [1j, 0]])
    return pauli_y
    
  def z(self):
    pauli_z = np.array([[1, 0],
                        [0, -1]])
    return pauli_z
  
  def r_theta(self, theta):
    e = np.e**(1j*theta)
    r = np.array([[1, 0],
                  [0, e]])
    return r
  
  def control_u(self, u):
    c_u = np.eye(4, dtype=np.complex128)
    c_u[2:, 2:]
    c_u[2:, 2:] = np.copy(u)
    return c_u

  def tensor_product(self, u1, u2):
    if self.checkunitary(u1) and self.checkunitary(u2):
      return np.kron(u1, u2)
    else:
      raise ValueError(f"Oops! either {u1} or {u2} is not a aunitary matrix")
    
  def adjoint(self, operator):
    """The transpose conjugate of the operator"""
    operator_transpose = np.copy(operator.T)
    return np.real(operator_transpose) + (-1j)*np.imag(operator_transpose)
  
  def checkunitary(self, operator):
    """Check if the operator is a unitary matrix"""
    size = np.shape(operator)[0]
    UU_T = operator.dot(self.adjoint(operator))
    print(f"operator\n {operator},\n adjoint\n {self.adjoint(operator)}")
    return np.allclose(UU_T,np.eye(size))

In [161]:
unitary = d2Unitary()

In [162]:
operator = 1/math.sqrt(2)*np.array([[1,1],
                                    [1,-1]])
print(operator)

[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]


In [163]:
unitary.checkunitary(operator) 

operator
 [[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]],
 adjoint
 [[ 0.70710678+0.j  0.70710678+0.j]
 [ 0.70710678+0.j -0.70710678+0.j]]


True

In [164]:
unitary.checkunitary(unitary.r_theta(np.pi/3))

operator
 [[1. +0.j        0. +0.j       ]
 [0. +0.j        0.5+0.8660254j]],
 adjoint
 [[1. +0.j        0. +0.j       ]
 [0. +0.j        0.5-0.8660254j]]


True

In [166]:
unitary.tensor_product(unitary.x(), unitary.i())

operator
 [[0 1]
 [1 0]],
 adjoint
 [[0.+0.j 1.+0.j]
 [1.+0.j 0.+0.j]]
operator
 [[1. 0.]
 [0. 1.]],
 adjoint
 [[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]


array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [203]:
class oneQubit:
  
  def __init__(self):
    self.state = np.array([1, 0], dtype=np.complex128).reshape(2,)
    
  def tensor(self, qubit):
    return np.kron(self.state, qubit.state)
  
  def inner(self, qubit):
    """q1.inner(q2) = <q1|q2>"""
    print(self.state.shape, qubit.state.shape)
    return np.conjugate(self.state).T.dot(qubit.state)
  
  def apply(self, operator=np.eye(2)):
    """Applys an operator on a state"""
    self.state = operator.dot(self.state)
    return self.state
  
  def display(self):
    print(f"{self.state[0]}|0> + {self.state[1]}|1>")
  
q1 = oneQubit()
q2 = oneQubit()

In [223]:
class ndQubit:
  
  def __init__(self, number_of_qubits):
    self.n = number_of_qubits
    self.state = self.initialize(number_of_qubits)
    
  def initialize(self, number_of_qubits):
    state = np.zeros((number_of_qubits**2), dtype=np.complex128).reshape(number_of_qubits**2, )
    state[0] = 1. + 0.j
    return state
  
  def display(self):
    for i in range(self.n**2):
      comp_basis_state = "{0:b}".format(i).zfill(self.n)
      plus = "+" if i != (self.n**2 - 1) else ""
      print(f"{self.state[i]}|{comp_basis_state}> {plus}", end=" ")
      
  def apply(self, operator=np.eye(2)):
    """Applys an operator on a state"""
    self.state = operator.dot(self.state)
    return self.state

In [224]:
qn = ndQubit(2)
qn.display()

(1+0j)|00> + 0j|01> + 0j|10> + 0j|11>  

In [362]:
# class GateNode:
#   def __init(self, gate_type=1, operation_number=0):
#     self.gate_type=gate_type
#     self.operation_number=operation_number

In [587]:
class SingleQubitGateNode:
  def __init__(self, gate, qubit_number, operation_number=0):
#     GateNode.__init__(self, gate_type=1, operation_number=operation_number)
    self.gate_type=1
    self.operation_number=operation_number
    self.gate = gate
    self.qubit_number = qubit_number
    self.next_gate_node = None

In [588]:
class TwoQubitControlGateNode:
  def __init__(self, gate, q1, q2, operation_number=0, gate_mat=np.eye(4)):
#     GateNode.__init__(self, gate_type=2, operation_number=operation_number)
    self.gate_type=2
    self.operation_number=operation_number
    self.gate = gate
    self.gate_mat = gate_mat
    self.control_qubit = q1
    self.target_qubit = q2
    self.next_gate_node = None

In [595]:
class GateGraph:
  
  def __init__(self, number_of_qubits):
    self.qubit_gate_nodes = self.fill_circuit(number_of_qubits)
    self.current_qubit_gate_nodes = [node for node in self.qubit_gate_nodes]
    self.operation_number = [0 for _ in range(number_of_qubits)]
    
    
  def fill_circuit(self, number_of_qubits):
    qubit_gate_nodes = []
    operation_number=0
    for i in range(number_of_qubits):
      qubit_gate_nodes.append(SingleQubitGateNode(gate="I", qubit_number=i, operation_number=operation_number))
    return qubit_gate_nodes
      
  def insert_single_qubit_gate(self, qubit_number, gate):
    ops_number = self.operation_number[qubit_number]
    self.operation_number[qubit_number]+=1
    new_gate_node = SingleQubitGateNode(gate=gate, qubit_number=qubit_number, 
                             operation_number=self.operation_number[qubit_number])    
    self.current_qubit_gate_nodes[qubit_number].next_gate_node = new_gate_node
    self.current_qubit_gate_nodes[qubit_number]=new_gate_node
    return
  
  def insert_two_qubit_gate(self, q1, q2, gate="2Q", gate_mat=np.eye(2)):
    ops_number_q1 = self.operation_number[q1]
    ops_number_q2 = self.operation_number[q2]
    ops_number = max(ops_number_q1, ops_number_q2)
    lower = min(q1, q2)
    upper = max(q1, q2)
    max_ops_number_in_range = ops_number
    for i in range(lower, upper+1, 1):
      max_ops_number_in_range=max(max_ops_number_in_range, self.current_qubit_gate_nodes[i].operation_number)
    for i in range(lower, upper+1, 1):
      self.operation_number[i]=max_ops_number_in_range+1
    new_gate_node = TwoQubitControlGateNode(gate=gate, q1=q1, q2=q2, 
                             operation_number=self.operation_number[q1], gate_mat=gate_mat)
    
    self.current_qubit_gate_nodes[q1].next_gate_node = new_gate_node
    self.current_qubit_gate_nodes[q1]=new_gate_node
    return

  def display_circuit(self):
    for idx, qubit_gate in enumerate(self.qubit_gate_nodes):
      print(f"|0>", end="")
      next_gate_for_qubit_i = qubit_gate.next_gate_node
      current_iter_number = 0
      while next_gate_for_qubit_i:
        for i in range(current_iter_number, next_gate_for_qubit_i.operation_number-1):
          print(f"--   --", end="")
        print(f"--{next_gate_for_qubit_i.gate}#{next_gate_for_qubit_i.operation_number}--", end="")
        current_iter_number=next_gate_for_qubit_i.operation_number
        next_gate_for_qubit_i=next_gate_for_qubit_i.next_gate_node
      print("\n") 

In [596]:
gg = GateGraph(4)
gg.insert_single_qubit_gate(1, "X")
gg.insert_single_qubit_gate(2, "Y")
gg.insert_two_qubit_gate(1, 0, "CU")
gg.insert_single_qubit_gate(2, "U")
gg.insert_single_qubit_gate(3, "U")
gg.insert_single_qubit_gate(0, "U")

In [597]:
gg.display_circuit()

|0>--   ----   ----U#3--

|0>--X#1----CU#2--

|0>--Y#1----U#2--

|0>--U#1--



In [598]:
for i in range(4):
  gg.insert_two_qubit_gate(i, 3-i, "CZ")
gg.display_circuit()

|0>--   ----   ----U#3----CZ#4--

|0>--X#1----CU#2----   ----   ----CZ#5--

|0>--Y#1----U#2----   ----   ----   ----CZ#6--

|0>--U#1----   ----   ----   ----   ----   ----CZ#7--



In [593]:
print(gg.qubit_gate_nodes)
print(gg.current_qubit_gate_nodes)

[<__main__.SingleQubitGateNode object at 0x1086c79a0>, <__main__.SingleQubitGateNode object at 0x1086c7d60>, <__main__.SingleQubitGateNode object at 0x1086c7910>, <__main__.SingleQubitGateNode object at 0x1086c7a00>]
[<__main__.TwoQubitControlGateNode object at 0x107f3a580>, <__main__.TwoQubitControlGateNode object at 0x107f3a790>, <__main__.TwoQubitControlGateNode object at 0x1082f1700>, <__main__.TwoQubitControlGateNode object at 0x1082f14f0>]


In [594]:
class GateGraphSimulator(GateGraph):
  def __init__(self, number_of_qubits):
    super().__init__(number_of_qubits)
  
  def simulate(self, number_of_shots):
    

IndentationError: expected an indented block (2740947031.py, line 6)

In [232]:
class Circuit(ndQubit, d2Unitary):
  
  def __init__(self, number_of_qubits):
    ndQubit.__init__(self, number_of_qubits)
    d2Unitary.__init__(self)
    self.gate_graph = GateGraph()
    
    
  def initialise_gates(self):
    gate_graph = {}
    for i in range(self.n):
      gate_graph[i] = []
    return gate_graph
      
  def i(self, nq):
    self.gate_graph[nq].append("I")
    return 
  def x(self, nq):
    self.gate_graph[nq].append("X")
    return
  
  def y(self, nq):
    self.gate_graph[nq].append("Y")
    return
    
  def z(self, nq):
    self.gate_graph[nq].append("Z")
    return
  
  def r_theta(self, theta, nq):
    self.gate_graph[nq].append("R")
    return
  
  def h(self, nq):
    self.gate_graph[nq].append("H")
    return
  
  def control_u(self, u, q1, q2):
    self.gate_graph[]
    
  def measure_all(self):
  
  def final_unitary(self):

In [233]:
quantumCirc = Circuit(2)

In [235]:
quantumCirc.gate_graph()

{0: [], 1: []}

In [ ]:
#   def display_circuit(self):
#     for idx, qubit_gate in enumerate(self.qubit_gate_nodes):
#       print(f"|0>", end="")
#       next_gate_for_qubit_i = qubit_gate.next_gate_node
#       while next_gate_for_qubit_i:
#         print(f"--{next_gate_for_qubit_i.gate}#{next_gate_for_qubit_i.operation_number}--", end="")
#         next_gate_for_qubit_i=next_gate_for_qubit_i.next_gate_node
#       print("\n")

    
#   def check_qubit_crossing(self, qubit_number, ops_number):
#     operation_number = ops_number
#     for gate_node in self.current_qubit_gate_nodes:
#       if gate_node.gate_type == 2:
#         q1 = gate_node.control_qubit
#         q2 = gate_node.target_qubit
        
#         lower = min(q1, q2)
#         upper = max(q1, q2)
#         print(f"qubit_number {qubit_number}, control {q1}, target {q2}, lower {lower}, upper {upper}, ops_number {ops_number}")
#         if (qubit_number >= lower) and (qubit_number <= upper):
#           operation_number = max(operation_number, gate_node.operation_number)
#     return operation_number + 1
  
#   def check_2_qubit_crossing(self, q1, q2, ops_number):
#     operation_number = ops_number
#     lower = min(q1, q2)
#     upper = max(q1, q2)
#     operation_number = ops_number
#     for gate_node in self.current_qubit_gate_nodes:
#       if gate_node.gate_type == 1:
#         qubit_number = gate_node.qubit_number
#         if (qubit_number >= lower) and (qubit_number <= upper):
#           operation_number = max(operation_number, gate_node.operation_number)
#       elif gate_node.gate_type == 2:
#         check_q1 = gate_node.control_qubit
#         check_q2 = gate_node.target_qubit
        
#         check_lower = min(check_q1, check_q2)
#         check_upper = max(check_q1, check_q2)
#         non_overlap_condition = (upper < check_lower) or (lower > check_upper)
#         if not non_overlap_condition:
#           operation_number = max(operation_number, gate_node.operation_number)
      
#     return operation_number + 1